# Generated by Django 3.2.8 on 2023-08-27 18:03

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(storage=blog.models.MediaStorage(), upload_to='blog_banners'),
        ),
    ]
