# Generated by Django 4.2.4 on 2023-08-29 10:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_blog_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
