# Generated by Django 3.2.8 on 2023-08-27 18:03

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20211129_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=user_profile.models.MediaStorage(), upload_to='profile_images'),
        ),
    ]
