# Generated by Django 4.2.4 on 2023-08-28 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0003_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="articles_or_blogs",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="awards_and_achievements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="education",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="events_attendance",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="hobbies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="projects",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="work_experience",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("twitter", "Twitter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("link", models.URLField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_info", models.CharField(max_length=150)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_infos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="user_contact_infos",
            field=models.ManyToManyField(
                blank=True, related_name="contact_infos", to="user_profile.contactinfo"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_social_media_links",
            field=models.ManyToManyField(
                blank=True, related_name="user_links", to="user_profile.socialmedialink"
            ),
        ),
    ]
