# Generated by Django 4.2.4 on 2023-08-28 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_profile",
            "0004_user_articles_or_blogs_user_awards_and_achievements_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_contact_infos",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_social_media_links",
        ),
        migrations.AddField(
            model_name="user",
            name="contact_infos",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_contact_infos",
                to="user_profile.contactinfo",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_media_links",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_social_media_links",
                to="user_profile.socialmedialink",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_contact_infos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_social_media_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="contact_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.contacttype",
            ),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.socialmediaplatform",
            ),
        ),
    ]
