# Generated by Django 4.2.4 on 2023-08-28 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0005_contacttype_socialmediaplatform_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmedialink",
            name="platform",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="articles_or_blogs",
        ),
        migrations.RemoveField(
            model_name="user",
            name="awards_and_achievements",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="contact_infos",
        ),
        migrations.RemoveField(
            model_name="user",
            name="education",
        ),
        migrations.RemoveField(
            model_name="user",
            name="events_attendance",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hobbies",
        ),
        migrations.RemoveField(
            model_name="user",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="user",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="user",
            name="social_media_links",
        ),
        migrations.RemoveField(
            model_name="user",
            name="work_experience",
        ),
        migrations.DeleteModel(
            name="ContactInfo",
        ),
        migrations.DeleteModel(
            name="ContactType",
        ),
        migrations.DeleteModel(
            name="SocialMediaLink",
        ),
        migrations.DeleteModel(
            name="SocialMediaPlatform",
        ),
    ]
