# Generated by Django 4.2.4 on 2023-08-29 10:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0007_user_bio_user_github_url_user_linkedin_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
