# Generated by Django 4.2.4 on 2023-09-01 12:26

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0008_alter_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
